language: scala

scala:
  - 2.12.8

script:
  - sbt clean coverage test

after_success:
  - sbt coverageReport
  - sbt coveralls
  - sbt codacyCoverage
  - bash <(curl -s https://codecov.io/bash)
  - sbt updateImpactSubmit
